config/routes.rb
Rails.application.routes.draw do

  post 'users', to: 'users#create'
  devise_for :users
  root to: 'pages#home'

  post '/newcellgoaltask', to: 'cell_goal#createTask', as: 'new_cell_task'
  get '/newcellgoal', to: 'cell_goal#new', as: 'cellgoal'
  post '/newcellgoal', to: 'cell_goal#create', as: 'create_cellgoal'
  get '/showcellgoal', to: 'cell_goal#show', as: 'show_cellgoal'

  post '/newdirectorshipgoaltask', to: 'directorship_goals#createTask', as: 'new_directorship_task'
  get '/newdirectorshipgoal', to: 'directorship_goals#new', as: 'directorshipgoal'
  post '/newdirectorshipgoal', to: 'directorship_goals#create', as: 'create_directorshipgoal'
  get '/showdirectorshipgoal', to: 'directorship_goals#show', as: 'show_directorshipgoal'

  post '/createpostcomment', to: 'posts#createComment', as: 'create_post_comment'

  post '/createarticlecomment', to: 'articles#createComment', as: 'create_article_comment'

  post '/addnewmembertoproject', to: 'projects#addNewMember', as: 'new_member'

  get '/mytasks', to: 'users#myTasks', as: 'mytasks'
  post 'updatecelltask', to: 'cell_goal#updateTask', as: 'update_cell_task'
  post 'updatedirtask', to: 'directorship_goals#updateTask', as: 'update_dir_task'


  post 'likespost', to: 'posts#like', as: 'post_like'
  post 'dislikepost', to: 'post#dislike', as: 'post_dislike'


  get '/skilltree', to: 'users#skilltree', as: 'skilltree'

  resources :users
  resources :posts do
    member do 
      put 'like' => 'posts#like'
    end
  end
  resources :articles do 
    member do 
      put 'like'=> 'articles#like'
    end
  end
  #put 'likearticle', to: 'articles#like', as: 'like_article'

  resources :skills

  resources :projects
  resources :cells
  resources :directorships
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :cell, optional: true
  belongs_to :directorship, optional: true
  has_many :project_users
  has_many :projects, through: :project_users
  has_many :skills
  has_many :articles
  has_many :posts 
  has_many :article_comments
  has_many :post_comments
  has_many :directorship_tasks
  has_many :cell_tasks
  acts_as_voter


  enum kind: { 
    member: 0,
    gp_director: 1,
    director: 2,
    project_director: 3,
    pmo_manager: 4,
    cell_manager: 5
}
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :skilltree]
  before_action :allow_only_gp, only: [:new, :create]
  before_action :set_cells, only: [:new, :edit]
  before_action :set_directorships, only: [:new, :edit]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    proj_users = ProjectUser.where(user_id: current_user.id)
    @ongoing_projects = []
    proj_users.each do |p_u|
      @ongoing_projects.push(Project.find(p_u.project_id))
    end

    #if proj.users_id.include?(@user.id)
    #   @user_projects.push(proj)
    #  end
    #end
    @user_ex_projects = []
    finished_prjects = Project.where(status: true)
    finished_prjects.each do |proj|
      if proj.users.include?(@user)
        @user_ex_projects.push(proj)
      end
    end

  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end


  def myTasks
    cell_tasks = CellTask.where(user_id: current_user.id)
    @undone_cell_tasks = cell_tasks.where(status: false)
    @done_cell_tasks = cell_tasks.where(status: true)
    dir_tasks = DirectorshipTask.where(user_id: current_user.id)
    @undone_dir_tasks = dir_tasks.where(status: false)
    @done_dir_tasks = dir_tasks.where(status: false)
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.password = '1234567'
    @user.password_confirmation = '1234567'
    if @user.save 
      redirect_to root_path
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def skilltree
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :name, :kind, :cell_id, :directorship_id)
    end

    def allow_only_gp
      unless current_user.kind == 'gp_director'
        redirect_to root_path
      end
    end

    def set_cells
      @cells = []
      Cell.all.each do |cell|
        aux = [cell.name, cell.id]
        @cells.push(aux)
      end
    end

    def set_directorships
      @directorships = []
      Directorship.all.each do |dir|
        aux = [dir.name, dir.id]
        @directorships.push(aux)
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
    def projects_of_current_user
        proj_users = ProjectUser.where(user_id: current_user.id)
        projs = []
        proj_users.each do |p_u|
            projs.push(Project.find(p_u.project_id))
        end
        return projs
    end
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Nome %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :Email %>
    <%= form.text_field :email %>
  </div>
  <div class="field select">
    <strong>Tipo de usuário:</strong>
    <%= select(:user, :kind, [
      ['Assessor', 'member'],
      ['Diretor de GP', 'gp_director'],
      ['Diretor', 'director'],
      ['Diretor de Projeto', 'project_director'],
      ['Gerente de PMO', 'pmo_manager'],
      ['Gerente de célula', 'cell_manager']
    ]) %>
    <br/>
  </div>
  <div class="field">
    <strong>Célula:</strong>
    <%= select(:user, :cell_id, cells) %>
  </div>
  <div class="field">
    <strong>Diretoria:</strong>
    <%= select(:user, :directorship_id, dirs) %>
  </div>

  <div class="actions text-right">
    <%= form.submit "Salvar", class:"btn btn-primary btn-new-dir" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container container-img-footprint">
    <div class="row">
        <%= link_to image_tag('back.svg'), users_path %>
        <%= link_to image_tag('show.svg', class:"img-show"), @user, class:"text-rigth" %>
    </div>
    <h1 class="h1-edit-user">Editar usuário</h1>

    <%= render 'form', user: @user, cells: @cells, dirs: @directorships %>

</div>

app/views/users/index.html.erb
<div class="container container-img-footprint">
  <p id="notice"><%= notice %></p>

  <h1 class="h1-users">Usuário</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Tipo</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.kind %></td>
          <td><%= link_to image_tag('show.svg'), user, class:"user-icon" %></td>
          <td><%= link_to image_tag('edit.svg'), edit_user_path(user), class:"user-icon" %></td>
          <td><%= link_to image_tag('destroy.svg'), user, method: :delete, data: { confirm: 'Deseja realmente excluir?' }, class:"user-icon" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
  <div class="actions text-right">
    <%= link_to 'Novo usuário', new_user_path, class:"btn btn-primary btn-new-dir" %>
  </div>
</div>

app/views/users/myTasks.html.erb
<div class="container container-img-footprint">
    <h1 class="h1-my-tasks"> Minha tarefas </h1>

    <div class="row">
        <div class="col-sm-6 text-center">
            <h3>Tarefas da célula</h3>
            <% @undone_cell_tasks.each do |task| %>
                <%=task.description %>
                <%= form_with(url: update_cell_task_path) do |form| %>
                    <%= form.hidden_field :id, :value => task.id %>
                    <%= form.submit "Concluído", :class => 'btn' %>
                <% end %>
            <% end %>           
        </div>
        <div class="col-sm-6 text-center">
            <h3> Tarefas da diretoria </h3>
            <% @undone_dir_tasks.each do |task| %>
                <%= task.description %>
                <%= form_with(url: update_dir_task_path) do |form| %>
                    <%= form.hidden_field :id, :value => task.id %>
                    <%= form.submit "Concluído", :class => 'btn' %>
                <% end %>
            <% end %>        
        </div>
    </div>


    <h2 class="mt-5"> Tarefas já concluídas: </h2>
    <table class="table">
        <% @done_cell_tasks.each do |task| %>
            <tr>
                <td><%= task.description %></td>
                <td>Concluída em: <%= task.updated_at %></td>
            </tr>
        <%end%>
        <% @done_dir_tasks.each do |task| %>
            <tr>
                <td><%= task.description %></td>
                <td>Concluída em: <%= task.updated_at %></td>
            </tr>
        <%end%>
    </table>
</div>

app/views/users/new.html.erb
<div class="container container-img-footprint">
    <%= link_to image_tag('back.svg'), users_path %>
    <h1 class="h1-new-user">Novo usuário</h1>

    <%= render 'form', user: @user, cells: @cells, dirs: @directorships  %>
</div>

app/views/users/show.html.erb
<div class="container container-user container-bottom">

  <div class="row">
      <%= link_to image_tag('back.svg'), users_path %>
      <%= link_to image_tag('edit.svg'), edit_user_path(@user), class: "img-edit" %>
  </div>
  <div class="row">
    <div class="col-sm-6 text-center image-profile">
      <%= image_tag('image-profile') %>
    </div>
    <div class="col-sm-6 text-center">
      <p class="description-user">
        <strong>Nome:</strong>
        <%= @user.name %>
      </p>

      <p class="description-user">
        <strong>Tipo:</strong>
        <%= @user.kind %>
      </p>

      <p class="description-user description-user-bottom">
        <strong>E-mail:</strong>
        <%= @user.email %>
      </p>
    </div>
  </div>
</div>
<div class="container container-user container-bottom">
  <p class="title-show">
    <strong>Célula atual:</strong>
    <%= @user.cell.name %>
  </p>
</div>
<div class="container container-user container-bottom">
  <p class="title-show">
    <strong>Diretoria atual:</strong>
    <%= @user.directorship.name %>
  </p>
</div>
<div class="container container-user container-bottom">
  <h4 class="title-show title-show-bold">Projetos em Andamento:</h4>
  <table class="table">
    <thead>
      <th>Projeto</th>
      <th>Descrição</th>
      <th>Criado em</th>
    <thead>
    <tbody>
      <% @ongoing_projects.each do |project| %>
        <tr>
          <td><%= project.title %></td>
          <td><%= project.description %></td>
          <td><%= project.created_at %></td>
        </tr>
      <%end%>
    </tbody>
  </table>
</div>
<div class="container container-user container-bottom">
  <h4 class="title-show title-show-bold">Projetos já Acabados:</h4>
  <table class="table">
    <thead>
      <th>Projeto</th>
      <th>Descrição</th>
      <th>Criado em</th>
    <thead>
    <tbody>
      <% @user_ex_projects.each do |project| %>
        <tr>
          <td><%= project.title %></td>
          <td><%= project.description %></td>
          <td><%= project.created_at %></td>
        </tr>
      <%end%>
    </tbody>
  </table>
  <br/>
</div>
<div class="container container-user container-bottom">
  <div class="actions text-center">
    <%= link_to  "Arvore de habilidade", skilltree_path(:id => @user.id) %>
  </div>
</div>
<br/>

app/views/users/skilltree.html.erb
<div class="container container-user">
    <%= link_to  image_tag('back.svg', class:"back"), @user %>
    <h1 class="h1-skilltree">Árvore de Habilidades de <%= @user.name %></h1>


    <table class="table">
        <thead>
            <th>Habilidade</th>
            <th>Descrição</th>
        </thead>
        <tbody>
            <% @user.skills.each do |skill| %>
                <tr>
                    <td><%= skill.name %></td>
                    <td><%= skill.description %></td>
                </tr>
            <%end%>
        </tbody>
    </table>

    <br/>

    
    <% if current_user == @user %>
        <%= link_to  "Adicionar Habilidade", new_skill_path(:id => @user.id) %>
    <%end%>
</div>