config/routes.rb
Rails.application.routes.draw do

  post 'users', to: 'users#create'
  devise_for :users
  root to: 'pages#home'

  post '/newcellgoaltask', to: 'cell_goal#createTask', as: 'new_cell_task'
  get '/newcellgoal', to: 'cell_goal#new', as: 'cellgoal'
  post '/newcellgoal', to: 'cell_goal#create', as: 'create_cellgoal'
  get '/showcellgoal', to: 'cell_goal#show', as: 'show_cellgoal'

  post '/newdirectorshipgoaltask', to: 'directorship_goals#createTask', as: 'new_directorship_task'
  get '/newdirectorshipgoal', to: 'directorship_goals#new', as: 'directorshipgoal'
  post '/newdirectorshipgoal', to: 'directorship_goals#create', as: 'create_directorshipgoal'
  get '/showdirectorshipgoal', to: 'directorship_goals#show', as: 'show_directorshipgoal'

  post '/createpostcomment', to: 'posts#createComment', as: 'create_post_comment'

  post '/createarticlecomment', to: 'articles#createComment', as: 'create_article_comment'

  post '/addnewmembertoproject', to: 'projects#addNewMember', as: 'new_member'

  get '/mytasks', to: 'users#myTasks', as: 'mytasks'
  post 'updatecelltask', to: 'cell_goal#updateTask', as: 'update_cell_task'
  post 'updatedirtask', to: 'directorship_goals#updateTask', as: 'update_dir_task'


  post 'likespost', to: 'posts#like', as: 'post_like'
  post 'dislikepost', to: 'post#dislike', as: 'post_dislike'


  get '/skilltree', to: 'users#skilltree', as: 'skilltree'

  resources :users
  resources :posts do
    member do 
      put 'like' => 'posts#like'
    end
  end
  resources :articles do 
    member do 
      put 'like'=> 'articles#like'
    end
  end
  #put 'likearticle', to: 'articles#like', as: 'like_article'

  resources :skills

  resources :projects
  resources :cells
  resources :directorships
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_comments

  acts_as_votable
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :like]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def createComment
    @comment = PostComment.new(post_comment_params)
    @comment.save
  end


  #Metodos do sistema de like
  def like
    if !current_user.liked? @post 
      @post.liked_by current_user 
    elsif current_user.liked? @post
      @post.unliked_by current_user
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:user_id, :title, :description)
    end

    def post_comment_params
      params.permit(:post_id, :user_id, :content)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.hidden_field :user_id, :value => current_user.id %>
  </div>

  <div class="field">
    <div class="form-group">
      <label for="inputsm"><%= form.label :title, "Título" %></br>
        <%= form.text_field :title, class: "form-control" %>
      </label>
    </div>
  </div>

  <div class="field">
    <div class="form-group">
      <label for="comment"><%= form.label :description, "Descrição" %>
        <%= form.text_area :description, class: "form-control" %>
      </label>
    </div>
  </div>

  <div class="actions text-right">
    <%= form.submit value: "Criar", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h1 class="posts">Fórum</h1>
  <table class="table">
    <% @posts.each do |post| %>
        <h2><%= link_to post.title, post %></h2>
        <br/>
        <p><%= post.description %></p>
        <p> Postado por: <%= link_to post.user.name, post.user %></p>
        <%= link_to "Like", like_post_path(post), method: :put, remote: :true %>
        <span class="likes-count"><%= post.get_upvotes.size %></span>
        <br/>
        <% post.post_comments.each do |comment| %>
          <%= comment.user.name %> comentou: <%= comment.content %>
          <br/>
        <%end%>
        <br/>
        <%= form_with(url: create_post_comment_path) do |form| %>
          <%= form.hidden_field :post_id, :value => post.id %>
          <%= form.hidden_field :user_id, :value => current_user.id %>
          <%= form.text_field :content %>
          <%= form.submit %>
        <%end%>
        <br/>
        <% if (current_user == post.user) || (current_user.kind == 'gp_director' || 'director' || 'project_director')%>
          <%= link_to 'Edit', edit_post_path(post) %>
          <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
        <%end%>
    <% end %>
  </table>
  
  <br>
  
  <%= link_to 'Criar Nova Postagem', new_post_path %>

</div>

app/views/posts/new.html.erb
<div class="container">
  <h1 class="new-post">Nova Postagem</h1>
  <div class="form-group">
    <%= render 'form', post: @post %>
  </div>
  <%= link_to 'Voltar', posts_path %>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>


<h1><%= @post.title %></h1>

<p>
  <strong>Post de:</strong>
  <%= link_to @post.user.name, @post.user %>
</p>

<p>
  <%= @post.description %>
</p>

<br>

<%= link_to "Like", like_post_path(@post), method: :put, remote: :true %>
<span class="likes-count"><%= @post.get_upvotes.size %></span>
<br>

<% @post.post_comments.each do |comment| %>
  <%= comment.user.name %> comentou: <%= comment.content %>
  <br/>
<%end%>
<br/>
<%= form_with(url: create_post_comment_path) do |form| %>
  <%= form.hidden_field :post_id, :value => @post.id %>
  <%= form.hidden_field :user_id, :value => current_user.id %>
  <%= form.text_field :content %>
  <%= form.submit%>
<%end%>


  <%= link_to 'Back', posts_path %>
<%if current_user == @post.user%>
  <%= link_to 'Edit', edit_post_path(@post) %>
<%end%>