config/routes.rb
Rails.application.routes.draw do

  post 'users', to: 'users#create'
  devise_for :users
  root to: 'pages#home'

  post '/newcellgoaltask', to: 'cell_goal#createTask', as: 'new_cell_task'
  get '/newcellgoal', to: 'cell_goal#new', as: 'cellgoal'
  post '/newcellgoal', to: 'cell_goal#create', as: 'create_cellgoal'
  get '/showcellgoal', to: 'cell_goal#show', as: 'show_cellgoal'

  post '/newdirectorshipgoaltask', to: 'directorship_goals#createTask', as: 'new_directorship_task'
  get '/newdirectorshipgoal', to: 'directorship_goals#new', as: 'directorshipgoal'
  post '/newdirectorshipgoal', to: 'directorship_goals#create', as: 'create_directorshipgoal'
  get '/showdirectorshipgoal', to: 'directorship_goals#show', as: 'show_directorshipgoal'

  post '/createpostcomment', to: 'posts#createComment', as: 'create_post_comment'

  post '/createarticlecomment', to: 'articles#createComment', as: 'create_article_comment'

  post '/addnewmembertoproject', to: 'projects#addNewMember', as: 'new_member'

  get '/mytasks', to: 'users#myTasks', as: 'mytasks'
  post 'updatecelltask', to: 'cell_goal#updateTask', as: 'update_cell_task'
  post 'updatedirtask', to: 'directorship_goals#updateTask', as: 'update_dir_task'


  post 'likespost', to: 'posts#like', as: 'post_like'
  post 'dislikepost', to: 'post#dislike', as: 'post_dislike'


  get '/skilltree', to: 'users#skilltree', as: 'skilltree'

  resources :users
  resources :posts do
    member do 
      put 'like' => 'posts#like'
    end
  end
  resources :articles do 
    member do 
      put 'like'=> 'articles#like'
    end
  end
  #put 'likearticle', to: 'articles#like', as: 'like_article'

  resources :skills

  resources :projects
  resources :cells
  resources :directorships
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cell.rb
class Cell < ApplicationRecord
  belongs_to :directorship
  has_many :users
  has_many :cell_goals
end

app/controllers/cells_controller.rb
class CellsController < ApplicationController
  before_action :set_cell, only: [:show, :edit, :update, :destroy]
  before_action :set_managers, only: [:new, :edit]
  before_action :set_directorships, only: [:new, :edit]

  # GET /cells
  # GET /cells.json
  def index
    @cells = Cell.all
  end


  # GET /cells/1
  # GET /cells/1.json
  def show
    @users = User.all
  end

  # GET /cells/new
  def new
    @cell = Cell.new
  end

  # GET /cells/1/edit
  def edit
  end

  # POST /cells
  # POST /cells.json
  def create
    @cell = Cell.new(cell_params)

    respond_to do |format|
      if @cell.save
        format.html { redirect_to @cell, notice: 'Célula criada com sucesso.' }
        format.json { render :show, status: :created, location: @cell }
      else
        format.html { render :new }
        format.json { render json: @cell.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cells/1
  # PATCH/PUT /cells/1.json
  def update
    respond_to do |format|
      if @cell.update(cell_params)
        format.html { redirect_to @cell, notice: 'Célula atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @cell }
      else
        format.html { render :edit }
        format.json { render json: @cell.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cells/1
  # DELETE /cells/1.json
  def destroy
    @cell.destroy
    respond_to do |format|
      format.html { redirect_to cells_url, notice: 'Célula excluída com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cell
      @cell = Cell.find(params[:id])
    end

    def set_managers
      @managers = []
      User.where(kind: "cell_manager").each do |manager|
        aux = [manager.name, manager.id]
        @managers.push(aux)
      end
    end

    def set_directorships
      @directorships = []
      Directorship.all.each do |dir|
        aux = [dir.name, dir.id]
        @directorships.push(aux)
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cell_params
      params.require(:cell).permit(:name, :manager, :directorship_id)
    end
end

app/helpers/cells_helper.rb
module CellsHelper
end

app/views/cells/_form.html.erb
<%= form_with(model: cell, local: true) do |form| %>
  <% if cell.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cell.errors.count, "error") %> proibiu que esta célula fosse salva:</h2>

      <ul>
      <% cell.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Nome %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :Diretor %>
    <%= form.select :manager, managers %>
  </div>

  <div class="field">
    <%= form.label :Diretoria %>
    <%= form.select :directorship_id, dirs %>
  </div>

  <div class="actions text-right">
    <%= form.submit "Salvar", class: "btn btn-primary btn-new-dir"%>
  </div>
<% end %>

app/views/cells/edit.html.erb
<div class="container container-img-footprint">
    <div class="row">
        <%= link_to image_tag('back.svg'), cells_path %>
        <%= link_to image_tag('show.svg', class:"img-show"), @cell, class:"text-right" %>
    </div>
    <h1 class="h1-edt-cell">Editar célula</h1>

    <%= render 'form', cell: @cell, managers: @managers, dirs: @directorships %>
</di

app/views/cells/index.html.erb
<div class="container container-img-footprint">
  <p id="notice"><%= notice %></p>
  <h1 class="h1-cells">Células</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Gerente</th>
        <th>Diretoria</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @cells.each do |cell| %>
        <tr>
          <td><%= cell.name %></td>
          <td><%= cell.manager %></td>
          <td><%= cell.directorship.name %></td>
          <td><%= link_to image_tag("show.svg"), cell, class: "cell-icon" %></td>
          <td><%= link_to image_tag("edit.svg"), edit_cell_path(cell), class: "cell-icon" %></td>
          <td><%= link_to image_tag("destroy.svg"), cell, method: :delete, data: { confirm: 'Deseja realmente excluir?' }, class: "cell-icon" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
  <div class="actions text-right">
    <%= link_to 'Nova Célula', new_cell_path, class: 'btn btn-primary btn-new-dir' %>
  <div>
</div>

app/views/cells/new.html.erb
<div class="container container-img-footprint">
    <%= link_to image_tag('back.svg'), cells_path %>
    <h1 class="h1-new-cell">Nova célula</h1>

    <%= render 'form', cell: @cell, managers: @managers, dirs: @directorships %>

    
</div>

app/views/cells/show.html.erb
<div class="container container-img-footprint">
  <p id="notice"><%= notice %></p>
  <div class="row">
    <%= link_to image_tag('back.svg'), cells_path, class: "icon-show img-back" %>
    <%= link_to image_tag('edit.svg'), edit_cell_path(@cell), class: "icon-show img-edit" %>
  </div>
  <div class="text-center">
    <%= image_tag ("group-wolf-suit.png"), class:"img-group-wolf-suit" %>
    <h1>Célula</h1>
  </div>
  

  <p>
    <strong class="show-title">Nome:</strong>
    <%= @cell.name %>
  </p>

  <p>
    <strong class="show-title">Gerente:</strong>
    <%= User.find(@cell.manager).name %>
  </p>

  <p>
    <strong class="show-title">Diretoria:</strong>
    <%= @cell.directorship.name %>
  </p>

  <table class="table">
    <tr>
      <h2>Integrantes</h2>
    </tr>
    <% @cell.users.each do |user| %>
      <td><%= link_to user.name, user,  class:"h3" %></td>
    <%end%>
  </table>

  
  <div class="card-group">
    <h2 class="mt-5">Metas</h2>
    <% @cell.cell_goals.each do |goal| %>
    <div class="card">
      <div class="card-body col-md-12 text-center">
        <strong>Nome da meta</strong> <br> <p class="text-goal"> <%= goal.title %> </p> <br>
        <strong>Status</strong> <br> <p class="text-goal"> <%if goal.status%>Sim<%else%>Não<%end%> </p> <br>
        <strong>Descrição</strong> <br> <p class="text-goal"> <%= goal.description %> </p> <br>
        <%= link_to 'Exibir meta', show_cellgoal_path(:id => goal.id), class:"btn btn-primary btn-goal" %>
      </div>
    </div>
    <%end%>
  </div>

  <div class="actions text-center">
    <%= link_to  "Criar nova meta", cellgoal_path(:id => @cell.id), class: "btn btn-primary btn-new-dir btn-new-goal" %>
  </div>
</div>